### ISSUE TITLE
performance issue?

### ISSUE THREAD

**Issue by jaapboerma** [BrianRosamilia/spaceEasel#1]
Hi Brian,

I liked this demo very much, but I was interested to know how the setup would perform with a few more players. Here's the result: 

![easel-16-screens](https://cloud.githubusercontent.com/assets/5254201/9273049/ae86bbe4-4288-11e5-8399-0e6838da6bae.gif)

As you can see, not all windows come to play. Any idea why?

**Comment by BrianRosamilia** [comment]
Wow thanks for the kind words!  :smiley_cat: and thanks for giving this a shot

I've had issues with chrome not being in focus when using websockets and having it not perform updates properly.  Try redoing this with FireFox or Safari; or if you have multiple machines try the same thing on your local network.   Given that the windows don't move at all I wouldn't say it's performance.

The windows that update are snappy.  For a single entity with many observers, once the oplog has been consumed, this is just a matter of in memory websockets pushing data which is very fast and scales way past 15 browsers!  There shouldn't really be any bottleneck with this demo (now if every browser had their own entity moving I'd be curious if things could degrade even at this few connections)

I'm definitely open to you trying the test again because I'd be interested in what the maximums really are.
